# Generated by Django 4.2 on 2023-04-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=500)),
                ('country_of_origin', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('publishing_date', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, unique=True)),
                ('store_manager', models.CharField(max_length=100)),
                ('store_location', models.CharField(max_length=100)),
                ('store_country', models.CharField(max_length=500)),
                ('founding_year', models.IntegerField(default=2000)),
                ('best_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_stores', to='api.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.CharField(max_length=500)),
                ('author_comments', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='api.book')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='members',
            field=models.ManyToManyField(through='api.BookAuthors', to='api.book'),
        ),
    ]
